{"name": "test_invalid_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Invalid67' in 'Invalid credentials'", "trace": "self = <tests.login_logout_test.TestLogin_logout object at 0x0000021787344200>\n\n    def test_invalid_login(self):\n        self.driver.get(config[\"base_url\"])\n        login_page = LoginPage(self.driver)\n        WebDriverWait(self.driver, config[\"timeout\"]).until(\n            EC.presence_of_element_located((By.XPATH, '//h5[text()=\"Login\"]')))\n        print(\"Login Page displayed\")\n        login_page.get_username_field().send_keys(config[\"username\"])\n        log.info(config[\"invalid_password\"])\n        login_page.get_password_field().send_keys(config[\"invalid_password\"])\n        login_page.get_submit_btn().click()\n        invalid_credentials_message = login_page.get_error_message_invalid_credentials().text\n        log.info(\"The Validation message after wrong Password :{}\".format(invalid_credentials_message))\n>       assert \"Invalid67\" in invalid_credentials_message\nE       AssertionError: assert 'Invalid67' in 'Invalid credentials'\n\nlogin_logout_test.py:47: AssertionError"}, "attachments": [{"name": "log", "source": "8f83b5c3-e035-49d5-a3f1-5abc78cae55c-attachment.txt", "type": "text/plain"}], "start": 1746356475998, "stop": 1746356478737, "uuid": "747eb1f3-ea09-44c8-aebf-aec48c502058", "historyId": "ad261a10614b8da93a70dd75956a8965", "testCaseId": "ad261a10614b8da93a70dd75956a8965", "fullName": "login_logout_test.TestLogin_logout#test_invalid_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'login')"}, {"name": "suite", "value": "login_logout_test"}, {"name": "subSuite", "value": "TestLogin_logout"}, {"name": "host", "value": "DESKTOP-5EGJGUV"}, {"name": "thread", "value": "13968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login_logout_test"}]}